
import React, { useState } from 'react';
import { Shield, Lock, FileText, CheckCircle } from 'lucide-react';

interface Props {
  onAccept: () => void;
}

export const LegalModal: React.FC<Props> = ({ onAccept }) => {
  const [scrolled, setScrolled] = useState(false);
  const [accepted, setAccepted] = useState(false);

  const handleScroll = (e: React.UIEvent<HTMLDivElement>) => {
    const bottom = e.currentTarget.scrollHeight - e.currentTarget.scrollTop === e.currentTarget.clientHeight;
    if (bottom) setScrolled(true);
  };

  return (
    <div className="fixed inset-0 bg-slate-900 z-[200] flex items-center justify-center p-4">
      <div className="bg-white max-w-2xl w-full rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        
        <div className="bg-slate-50 p-6 border-b border-slate-200">
          <div className="flex items-center gap-3 mb-2">
             <div className="bg-slate-900 text-white p-2 rounded-lg">
               <Shield size={24} />
             </div>
             <h2 className="text-2xl font-serif font-bold text-slate-900">Terms of Service</h2>
          </div>
          <p className="text-sm text-slate-500">
            Please read and accept the End User License Agreement (EULA) to use FinStruct India.
          </p>
        </div>

        <div 
          className="flex-1 overflow-y-auto p-8 text-sm text-slate-600 leading-relaxed bg-slate-50/50 inner-shadow"
          onScroll={handleScroll}
        >
           <h3 className="font-bold text-slate-900 mb-2">1. Intellectual Property Rights</h3>
           <p className="mb-4">
             The software "FinStruct India", including its source code, algorithms, financial models, and UI design, is the exclusive intellectual property of the Developer. You are granted a limited, non-exclusive, non-transferable license to use the software for business purposes. You may not reverse engineer, decompile, or copy the source code.
           </p>

           <h3 className="font-bold text-slate-900 mb-2">2. Data Privacy & Security</h3>
           <p className="mb-4">
             This application operates on a "Zero-Knowledge" architecture. Your financial data is encrypted locally on your device using AES-256 encryption before being stored. The Developer has no access to your raw data, passwords, or generated reports. You are solely responsible for maintaining the confidentiality of your Master Password.
           </p>

           <h3 className="font-bold text-slate-900 mb-2">3. Disclaimer of Liability</h3>
           <p className="mb-4">
             The reports generated by this AI tool are for estimation and drafting purposes only. They do not constitute certified financial advice. All Detailed Project Reports (DPR) must be verified and signed by a qualified Chartered Accountant (CA) before submission to any bank or financial institution. The Developer is not liable for loan rejections.
           </p>

           <h3 className="font-bold text-slate-900 mb-2">4. Governing Law</h3>
           <p className="mb-4">
             This agreement is governed by the laws of India. Any disputes regarding the ownership or usage of this software shall be subject to the jurisdiction of courts in [Your City], India.
           </p>
           
           <div className="h-12"></div>
        </div>

        <div className="p-6 bg-white border-t border-slate-200">
           <label className="flex items-center gap-3 p-4 rounded-lg border border-slate-200 cursor-pointer hover:bg-slate-50 transition mb-4">
              <div className={`w-5 h-5 rounded border flex items-center justify-center ${accepted ? 'bg-amber-500 border-amber-500 text-white' : 'border-slate-300'}`}>
                 {accepted && <CheckCircle size={14} />}
              </div>
              <input type="checkbox" className="hidden" checked={accepted} onChange={e => setAccepted(e.target.checked)} />
              <span className="text-sm font-medium text-slate-700">I agree to the Terms of Service and Privacy Policy</span>
           </label>

           <button 
             onClick={onAccept}
             disabled={!accepted}
             className="w-full bg-slate-900 text-white py-4 rounded-xl font-bold disabled:opacity-50 disabled:cursor-not-allowed hover:bg-slate-800 transition flex items-center justify-center gap-2"
           >
             <Lock size={18} /> Enter Secure Application
           </button>
        </div>

      </div>
    </div>
  );
};
