
import * as XLSX from 'xlsx';
import { FullReport } from '../types';

export const generateCMAExcel = (report: FullReport) => {
  const wb = XLSX.utils.book_new();

  // --- Sheet 1: Assumptions & Inputs ---
  const inputsData = [
    ["CMA DATA - KEY ASSUMPTIONS & INPUTS"],
    ["Generated by FinStruct India"],
    [""],
    ["Entity Details"],
    ["Business Name", report.data.entityName],
    ["Type", report.data.entityType],
    ["Promoter", report.data.promoterName],
    ["Location", report.data.location],
    [""],
    ["Project Cost Breakdown (₹ Lakhs)"],
    ["Land", report.data.financials.landCost],
    ["Building", report.data.financials.buildingCost],
    ["Plant & Machinery", report.data.financials.machineryCost],
    ["Working Capital Margin", report.data.financials.workingCapitalCost],
    ["Contingencies/Others", report.data.financials.otherCost],
    ["Total Project Cost", report.data.financials.projectCost],
    [""],
    ["Means of Finance (₹ Lakhs)"],
    ["Own Contribution (Equity)", report.data.financials.ownContribution],
    ["Term Loan Required", report.data.financials.loanRequired],
    [""],
    ["Key Financial Assumptions"],
    ["Interest Rate", `${report.data.financials.interestRate}%`],
    ["Loan Tenure", `${report.data.financials.loanTenure} Years`],
    ["Income Tax Rate", `${report.data.financials.incomeTaxRate}%`],
    ["Depreciation (Building)", `${report.data.financials.depreciationBuilding}%`],
    ["Depreciation (Machinery)", `${report.data.financials.depreciationMachinery}%`],
    [""],
    ["Key Metrics"],
    ["IRR", `${report.metrics.irr}%`],
    ["NPV", `₹${report.metrics.npv}`],
    ["Avg DSCR", report.metrics.avgDscr]
  ];
  const wsInputs = XLSX.utils.aoa_to_sheet(inputsData);
  XLSX.utils.book_append_sheet(wb, wsInputs, "Assumptions");

  // --- Sheet 2: Profit & Loss ---
  const yearsHeader = report.projections.map(p => `Year ${p.year}`);
  const plData = [
    ["PROJECTED PROFIT & LOSS STATEMENT (₹ Lakhs)", ...yearsHeader.map(() => "")],
    ["Particulars", ...yearsHeader],
    ["Revenue from Operations", ...report.projections.map(p => p.revenue)],
    ["Less: Expenses", ...report.projections.map(p => p.expense)],
    ["EBITDA", ...report.projections.map(p => p.ebitda)],
    ["Less: Interest", ...report.projections.map(p => p.interest)],
    ["Less: Depreciation", ...report.projections.map(p => p.depreciation)],
    ["Profit Before Tax (PBT)", ...report.projections.map(p => p.pbt)],
    ["Less: Tax", ...report.projections.map(p => p.tax)],
    ["Profit After Tax (PAT)", ...report.projections.map(p => p.pat)]
  ];
  const wsPL = XLSX.utils.aoa_to_sheet(plData);
  XLSX.utils.book_append_sheet(wb, wsPL, "Profit & Loss");

  // --- Sheet 3: Balance Sheet ---
  const bsData = [
    ["PROJECTED BALANCE SHEET (₹ Lakhs)", ...yearsHeader.map(() => "")],
    ["Liabilities", ...yearsHeader],
    ["Share Capital", ...report.projections.map(p => p.shareCapital)],
    ["Reserves & Surplus", ...report.projections.map(p => p.reserves)],
    ["Long Term Borrowings", ...report.projections.map(p => p.longTermLoan)],
    ["Current Liabilities", ...report.projections.map(p => 0)], // Simplified
    ["Total Liabilities", ...report.projections.map(p => p.totalLiabilities)],
    [""],
    ["Assets", ...yearsHeader],
    ["Net Fixed Assets", ...report.projections.map(p => p.netFixedAssets)],
    ["Current Assets", ...report.projections.map(p => p.currentAssets)],
    ["Total Assets", ...report.projections.map(p => p.totalAssets)]
  ];
  const wsBS = XLSX.utils.aoa_to_sheet(bsData);
  XLSX.utils.book_append_sheet(wb, wsBS, "Balance Sheet");

  // --- Sheet 4: Cash Flow ---
  const cfData = [
    ["PROJECTED CASH FLOW STATEMENT (₹ Lakhs)", ...yearsHeader.map(() => "")],
    ["Particulars", ...yearsHeader],
    ["Net Profit After Tax", ...report.projections.map(p => p.pat)],
    ["Add: Depreciation", ...report.projections.map(p => p.depreciation)],
    ["Cash Accruals", ...report.projections.map(p => p.pat + p.depreciation)],
    ["Less: Loan Repayment", ...report.projections.map(p => {
         const repayment = (report.data.financials.loanRequired / 7);
         return p.year <= 7 ? repayment : 0;
    })],
    ["Net Surplus / (Deficit)", ...report.projections.map(p => p.cashFlow)]
  ];
  const wsCF = XLSX.utils.aoa_to_sheet(cfData);
  XLSX.utils.book_append_sheet(wb, wsCF, "Cash Flow");

  // --- Sheet 5: Amortization Schedule ---
  if (report.amortization && report.amortization.length > 0) {
      const amortData = [
          ["LOAN AMORTIZATION SCHEDULE (₹ Lakhs)"],
          ["Year", "Opening Balance", "Interest", "Principal", "Closing Balance"],
          ...report.amortization.map(a => [a.year, a.openingBalance, a.interest, a.principal, a.closingBalance])
      ];
      const wsAmort = XLSX.utils.aoa_to_sheet(amortData);
      XLSX.utils.book_append_sheet(wb, wsAmort, "Loan Schedule");
  }

  // --- Sheet 6: Working Capital ---
  if (report.workingCapital && report.workingCapital.length > 0) {
      const wcData = [
          ["ASSESSMENT OF WORKING CAPITAL (₹ Lakhs) - MPBF Method"],
          ["Year", "Inventory", "Receivables", "Payables", "Net WC Gap", "MPBF (75%)"],
          ...report.workingCapital.map(w => [w.year, w.inventory, w.receivables, w.payables, w.netWorkingCapital, w.bankFinance])
      ];
      const wsWC = XLSX.utils.aoa_to_sheet(wcData);
      XLSX.utils.book_append_sheet(wb, wsWC, "Working Capital");
  }

  // Write File
  XLSX.writeFile(wb, `${report.data.entityName.replace(/\s+/g, '_')}_CMA_Report.xlsx`);
};
