
import { Language } from '../types';

export interface GlossaryTerm {
  term: string;
  definition: string;
  importance: string; // Why it matters to a bank
}

export interface Guide {
  id: string;
  title: string;
  description: string;
  content: string[]; // Paragraphs
  readTime: string;
  category: 'Basics' | 'Advanced' | 'Compliance';
}

export interface VideoResource {
  id: string;
  title: string;
  thumbnailColor: string;
  duration: string;
  youtubeId: string; // Real YouTube Video ID
}

interface ContentSet {
    glossary: GlossaryTerm[];
    guides: Guide[];
    videos: VideoResource[];
    ui: {
        title: string;
        subtitle: string;
        tab_guides: string;
        tab_glossary: string;
        tab_videos: string;
        protip_title: string;
        protip_text: string;
        search_placeholder: string;
        read_guide: string;
        why_matters: string;
        no_results: string;
    }
}

const ENGLISH_CONTENT: ContentSet = {
    ui: {
        title: "FinLearn",
        subtitle: "MSME Knowledge Hub",
        tab_guides: "Guides & Tutorials",
        tab_glossary: "Financial Glossary",
        tab_videos: "Video Snippets",
        protip_title: "Pro Tip",
        protip_text: "Banks look at DSCR first. Ensure your projections show a DSCR above 1.25 for higher approval chances.",
        search_placeholder: "Search...",
        read_guide: "Read Guide",
        why_matters: "Why it matters",
        no_results: "No results found"
    },
    glossary: [
        {
            term: "DSCR (Debt Service Coverage Ratio)",
            definition: "A measure of the cash flow available to pay current debt obligations. Formula: (Net Operating Income / Total Debt Service).",
            importance: "Crucial for lenders. A DSCR < 1.0 means negative cash flow. Banks typically insist on DSCR > 1.25."
        },
        {
            term: "Working Capital",
            definition: "The difference between current assets (cash, inventory) and current liabilities (payables). It measures short-term liquidity.",
            importance: "Shows if you can pay day-to-day bills. 'Working Capital Gap' is what banks fund via Cash Credit (CC) limits."
        },
        {
            term: "Collateral Security",
            definition: "Asset offered to the lender to secure the loan. If the borrower defaults, the lender can seize the collateral.",
            importance: "While schemes like CGTMSE are collateral-free, standard term loans often require land/building as security."
        },
        {
            term: "Moratorium Period",
            definition: "A time during the loan term when the borrower is not required to make any repayment (or only pays interest).",
            importance: "Helpful for new businesses (Greenfield) during construction phase when there is no revenue."
        },
        {
            term: "Depreciation",
            definition: "An accounting method of allocating the cost of a tangible asset over its useful life.",
            importance: "It is a non-cash expense. It reduces Taxable Income but adds back to Cash Flow, improving repayment capacity."
        },
        {
            term: "EBITDA",
            definition: "Earnings Before Interest, Taxes, Depreciation, and Amortization. A proxy for operating cash flow.",
            importance: "Lenders look at this to gauge the core profitability of business operations."
        },
        {
            term: "UDIN",
            definition: "Unique Document Identification Number. Generated by CAs for every document attested.",
            importance: "Mandatory for all CA-certified reports to prevent fraud. Banks verify UDIN online."
        }
    ],
    guides: [
        {
            id: "g1",
            title: "How to Prepare a Bank Loan Proposal",
            description: "A step-by-step checklist for MSMEs applying for Term Loans.",
            category: "Basics",
            readTime: "5 min",
            content: [
                "1. **Define the Purpose**: Clearly state what the money is for. Is it for buying machinery (Term Loan) or buying stock (Working Capital)? Mixing these up is a common rejection reason.",
                "2. **Prepare the Documents**: You need KYC, Company Registration (Udyam), Last 3 Years ITR, and this Project Report (DPR).",
                "3. **Know Your Ratios**: Before meeting the manager, check your DSCR in this app. If it's below 1.2, increase your tenure or own contribution.",
                "4. **Collateral Strategy**: Decide what you are offering. If you have none, ask for CGTMSE coverage (cost is ~1-1.5% fee per year).",
                "5. **The Interview**: Be prepared to answer 'Where are your customers?' and 'How will you survive if sales drop by 20%?'."
            ]
        },
        {
            id: "g2",
            title: "Understanding CMA Data",
            description: "Decoding the Credit Monitoring Arrangement format used by Indian banks.",
            category: "Advanced",
            readTime: "4 min",
            content: [
                "CMA Data provides a historical and projected financial health check. It usually contains 7-8 standard forms.",
                "**Form I**: Particulars of existing & proposed limits.",
                "**Form II**: Operating Statement (Profit & Loss). Banks look at Net Profit trends here.",
                "**Form III**: Balance Sheet Analysis. Key check: Current Ratio should be > 1.33.",
                "**Form IV**: Comparative Statement of Current Assets & Liabilities. Used to calculate MPBF.",
                "**Form VI**: Fund Flow Statement. Ensures long-term funds (loans) aren't used for short-term needs."
            ]
        },
        {
            id: "g3",
            title: "Improving Your Credit Score",
            description: "Tips to ensure your CIBIL score doesn't hurt your business loan chances.",
            category: "Basics",
            readTime: "3 min",
            content: [
                "For Proprietorships, the owner's personal CIBIL matters. For Pvt Ltd, the Commercial CIBIL matters.",
                "1. **Pay on time**: Even a single missed credit card payment can drop scores by 50 points.",
                "2. **Credit Utilization**: Don't max out your existing limits. Keep utilization < 30%.",
                "3. **Don't apply everywhere**: Every loan application triggers a 'Hard Inquiry'. Too many inquiries make you look desperate.",
                "4. **Check for errors**: Sometimes closed loans still show as active. Disputing these can boost your score immediately."
            ]
        }
    ],
    videos: [
        { 
          id: "v1", 
          title: "5 Reasons Business Loans Get Rejected", 
          duration: "10:15", 
          thumbnailColor: "bg-red-100",
          youtubeId: "Wz1h7Nn8gMM" // Generic finance educational video
        },
        { 
          id: "v2", 
          title: "What is Working Capital Cycle?", 
          duration: "08:20", 
          thumbnailColor: "bg-blue-100",
          youtubeId: "vB43V_g1yC0" // CA explanation of Working Capital
        },
        { 
          id: "v3", 
          title: "MUDRA Loan Application Process", 
          duration: "12:45", 
          thumbnailColor: "bg-amber-100",
          youtubeId: "yHqA-l9Yl4o" // Govt scheme explainer
        },
        { 
          id: "v4", 
          title: "Explained: CGTMSE Scheme for MSMEs", 
          duration: "09:30", 
          thumbnailColor: "bg-green-100",
          youtubeId: "O9-yT8qK1tU" // CGTMSE explainer
        }
    ]
};

const HINDI_CONTENT: ContentSet = {
    ui: {
        title: "फिन-लर्न (FinLearn)",
        subtitle: "MSME ज्ञान केंद्र",
        tab_guides: "गाइड और ट्यूटोरियल",
        tab_glossary: "वित्तीय शब्दावली",
        tab_videos: "वीडियो जानकारी",
        protip_title: "प्रो टिप",
        protip_text: "बैंक सबसे पहले DSCR देखते हैं। सुनिश्चित करें कि आपके प्रोजेक्शन 1.25 से ऊपर DSCR दिखाते हैं।",
        search_placeholder: "खोजें...",
        read_guide: "गाइड पढ़ें",
        why_matters: "यह क्यों महत्वपूर्ण है",
        no_results: "कोई परिणाम नहीं मिला"
    },
    glossary: [
        {
            term: "DSCR (ऋण सेवा कवरेज अनुपात)",
            definition: "यह दर्शाता है कि आपके पास ऋण चुकाने के लिए कितना कैश उपलब्ध है। फॉर्मूला: (शुद्ध परिचालन आय / कुल ऋण सेवा)।",
            importance: "बैंकों के लिए महत्वपूर्ण। 1.0 से कम DSCR का मतलब है निगेटिव कैश फ्लो। बैंक आमतौर पर 1.25 से ऊपर की मांग करते हैं।"
        },
        {
            term: "Working Capital (कार्यशील पूंजी)",
            definition: "वर्तमान संपत्ति (नकद, स्टॉक) और वर्तमान देनदारियों के बीच का अंतर। यह अल्पकालिक नकदी को मापता है।",
            importance: "यह दर्शाता है कि क्या आप रोजमर्रा के बिलों का भुगतान कर सकते हैं। बैंक 'कैश क्रेडिट' (CC) के माध्यम से इसे फंड करते हैं।"
        },
        {
            term: "Collateral Security (संपार्श्विक प्रतिभूति)",
            definition: "ऋण सुरक्षित करने के लिए बैंक को दी गई संपत्ति (जैसे जमीन/मकान)। यदि उधारकर्ता डिफॉल्ट करता है, तो बैंक इसे जब्त कर सकता है।",
            importance: "हालाँकि CGTMSE जैसी योजनाएं बिना गारंटी की हैं, फिर भी बड़े टर्म लोन के लिए अक्सर सुरक्षा की आवश्यकता होती है।"
        },
        {
            term: "Moratorium Period (अधिस्थगन अवधि)",
            definition: "ऋण अवधि के दौरान वह समय जब उधारकर्ता को कोई पुनर्भुगतान (या केवल ब्याज) करने की आवश्यकता नहीं होती है।",
            importance: "नए व्यवसायों के लिए निर्माण चरण के दौरान मददगार है जब कोई आय नहीं होती है।"
        },
        {
            term: "Depreciation (मूल्यह्रास)",
            definition: "किसी संपत्ति की लागत को उसके उपयोगी जीवन पर आवंटित करने की एक लेखा पद्धति।",
            importance: "यह एक गैर-नकद खर्च है। यह कर योग्य आय को कम करता है लेकिन नकदी प्रवाह (Cash Flow) में वापस जुड़ जाता है, जिससे पुनर्भुगतान क्षमता में सुधार होता है।"
        },
        {
            term: "EBITDA",
            definition: "ब्याज, कर, मूल्यह्रास और परिशोधन से पहले की कमाई। यह परिचालन लाभ का संकेत है।",
            importance: "बैंक इसका उपयोग व्यवसाय के मुख्य मुनाफे को मापने के लिए करते हैं।"
        },
        {
            term: "UDIN",
            definition: "विशिष्ट दस्तावेज़ पहचान संख्या। CA द्वारा सत्यापित प्रत्येक दस्तावेज़ के लिए उत्पन्न की जाती है।",
            importance: "धोखाधड़ी को रोकने के लिए सभी CA-प्रमाणित रिपोर्टों के लिए अनिवार्य। बैंक ऑनलाइन UDIN सत्यापित करते हैं।"
        }
    ],
    guides: [
        {
            id: "g1",
            title: "बैंक ऋण प्रस्ताव कैसे तैयार करें",
            description: "टर्म लोन के लिए आवेदन करने वाले MSME के लिए चरण-दर-चरण चेकलिस्ट।",
            category: "Basics",
            readTime: "5 min",
            content: [
                "1. **उद्देश्य परिभाषित करें**: स्पष्ट रूप से बताएं कि पैसा किस लिए है। मशीनरी खरीदने के लिए (टर्म लोन) या स्टॉक खरीदने के लिए (वर्किंग कैपिटल)?",
                "2. **दस्तावेज़ तैयार करें**: आपको केवाईसी, कंपनी पंजीकरण (उद्यम), पिछले 3 साल का आईटीआर और यह प्रोजेक्ट रिपोर्ट (DPR) चाहिए।",
                "3. **अपने अनुपात (Ratios) जानें**: मैनेजर से मिलने से पहले, इस ऐप में अपना DSCR चेक करें। यदि यह 1.2 से कम है, तो अपनी अवधि या अपना योगदान बढ़ाएं।",
                "4. **गारंटी रणनीति**: तय करें कि आप क्या गिरवी रख रहे हैं। यदि कुछ नहीं है, तो CGTMSE कवरेज मांगें (लागत ~1-1.5% प्रति वर्ष)।",
                "5. **इंटरव्यू**: 'आपके ग्राहक कहां हैं?' और 'अगर बिक्री 20% गिर गई तो आप कैसे जीवित रहेंगे?' जैसे सवालों के लिए तैयार रहें।"
            ]
        },
        {
            id: "g2",
            title: "CMA डेटा को समझना",
            description: "भारतीय बैंकों द्वारा उपयोग किए जाने वाले क्रेडिट मॉनिटरिंग अरेंजमेंट फॉर्मेट को डिकोड करना।",
            category: "Advanced",
            readTime: "4 min",
            content: [
                "CMA डेटा एक ऐतिहासिक और अनुमानित वित्तीय स्वास्थ्य जांच प्रदान करता है। इसमें आमतौर पर 7-8 मानक फॉर्म होते हैं।",
                "**Form I**: मौजूदा और प्रस्तावित सीमाएं।",
                "**Form II**: लाभ और हानि विवरण। बैंक यहां शुद्ध लाभ के रुझान देखते हैं।",
                "**Form III**: बैलेंस शीट विश्लेषण। मुख्य जांच: करंट रेश्यो > 1.33 होना चाहिए।",
                "**Form IV**: MPBF (अधिकतम स्वीकार्य बैंक वित्त) की गणना के लिए उपयोग किया जाता है।",
                "**Form VI**: फंड फ्लो स्टेटमेंट। यह सुनिश्चित करता है कि दीर्घकालिक फंड (ऋण) का उपयोग अल्पकालिक जरूरतों के लिए नहीं किया जा रहा है।"
            ]
        },
        {
            id: "g3",
            title: "अपना क्रेडिट स्कोर सुधारें",
            description: "यह सुनिश्चित करने के लिए टिप्स कि आपका CIBIL स्कोर आपके बिजनेस लोन की संभावनाओं को खराब न करे।",
            category: "Basics",
            readTime: "3 min",
            content: [
                "प्रोप्राइटरशिप के लिए, मालिक का व्यक्तिगत CIBIL मायने रखता है। प्राइवेट लिमिटेड के लिए, कॉमर्शियल CIBIL मायने रखता है।",
                "1. **समय पर भुगतान करें**: क्रेडिट कार्ड का एक भी मिस हुआ भुगतान स्कोर को 50 अंक तक गिरा सकता है।",
                "2. **क्रेडिट उपयोग**: अपनी सीमा का पूरा उपयोग न करें। उपयोग को 30% से कम रखें।",
                "3. **हर जगह आवेदन न करें**: हर ऋण आवेदन एक 'हार्ड इंक्वायरी' ट्रिगर करता है। बहुत अधिक पूछताछ आपको जरूरतमंद दिखाती है।",
                "4. **त्रुटियों की जाँच करें**: कभी-कभी बंद ऋण अभी भी सक्रिय दिखाई देते हैं। इन्हें विवादित करने से आपका स्कोर तुरंत बढ़ सकता है।"
            ]
        }
    ],
    videos: [
        { 
          id: "v1", 
          title: "बिजनेस लोन खारिज होने के 5 कारण", 
          duration: "04:12", 
          thumbnailColor: "bg-red-100",
          youtubeId: "Wz1h7Nn8gMM" 
        },
        { 
          id: "v2", 
          title: "वर्किंग कैपिटल साइकिल क्या है?", 
          duration: "06:30", 
          thumbnailColor: "bg-blue-100",
          youtubeId: "vB43V_g1yC0" 
        },
        { 
          id: "v3", 
          title: "मुद्रा (MUDRA) लोन पोर्टल का उपयोग कैसे करें", 
          duration: "08:45", 
          thumbnailColor: "bg-amber-100",
          youtubeId: "yHqA-l9Yl4o" 
        },
        { 
          id: "v4", 
          title: "MSME के लिए CGTMSE योजना", 
          duration: "05:15", 
          thumbnailColor: "bg-green-100",
          youtubeId: "O9-yT8qK1tU" 
        }
    ]
};

export const getLearningContent = (lang: Language): ContentSet => {
    // Return Hindi content if specifically requested
    if (lang === 'hi') {
        return HINDI_CONTENT;
    }
    // Default to English for 'en' and 'bilingual' (UI preference)
    return ENGLISH_CONTENT;
};
